In [ ]:
# PyTorch Tutorial
# Getting started

In [2]:
from __future__ import print_function

LOG = True
def logg(x):
    if LOG:
        print(x)
    else:
        p
import torch


In [4]:
x = torch.Tensor(5, 3)
print(x)
print(x.size())


 0.0000e+00  0.0000e+00 -1.2296e+27
 4.5692e-41 -4.0954e+24  4.5692e-41
 1.2815e-38  0.0000e+00  1.2815e-38
 0.0000e+00 -2.5098e-01  4.5692e-41
-2.5099e-01  4.5692e-41 -2.5099e-01
[torch.FloatTensor of size 5x3]

torch.Size([5, 3])


In [7]:
y = torch.rand(5,3)
print(x+y)
print(torch.add(x,y))


 2.1275e-01  8.6222e-01 -1.2296e+27
 8.4586e-01 -4.0954e+24  2.1688e-01
 2.5537e-01  8.7649e-01  8.8704e-01
 9.3219e-01  4.9824e-01  3.1670e-01
 4.4856e-01  4.8176e-01  2.3892e-01
[torch.FloatTensor of size 5x3]


 2.1275e-01  8.6222e-01 -1.2296e+27
 8.4586e-01 -4.0954e+24  2.1688e-01
 2.5537e-01  8.7649e-01  8.8704e-01
 9.3219e-01  4.9824e-01  3.1670e-01
 4.4856e-01  4.8176e-01  2.3892e-01
[torch.FloatTensor of size 5x3]



In [ ]:
# Give the output to a tensor
result = torch.Tensor(5,3)
torch.add(x, y, out=result)
print(result)

In [8]:
# Addition in-place
y.add_(x)
print(y)


 2.1275e-01  8.6222e-01 -1.2296e+27
 8.4586e-01 -4.0954e+24  2.1688e-01
 2.5537e-01  8.7649e-01  8.8704e-01
 9.3219e-01  4.9824e-01  3.1670e-01
 4.4856e-01  4.8176e-01  2.3892e-01
[torch.FloatTensor of size 5x3]



In [10]:
# Indexing: like numpy syntax
print(x)
print(x[:,1])


 0.0000e+00  0.0000e+00 -1.2296e+27
 4.5692e-41 -4.0954e+24  4.5692e-41
 1.2815e-38  0.0000e+00  1.2815e-38
 0.0000e+00 -2.5098e-01  4.5692e-41
-2.5099e-01  4.5692e-41 -2.5099e-01
[torch.FloatTensor of size 5x3]


 0.0000e+00
-4.0954e+24
 0.0000e+00
-2.5098e-01
 4.5692e-41
[torch.FloatTensor of size 5]



In [13]:
# Resizing
x = torch.randn(4,4)
y = x.view(16)
print(x)
print(y)
z = x.view(-1, 8) # -1 used to infer size from other dimensions
print(z)




 0.0506 -0.8122  0.1810 -0.5836
-0.4300 -0.9669  0.5346  0.7780
-0.9813  0.0706  0.5063  0.7313
 0.3003  1.8423  0.2580 -1.4946
[torch.FloatTensor of size 4x4]


 0.0506
-0.8122
 0.1810
-0.5836
-0.4300
-0.9669
 0.5346
 0.7780
-0.9813
 0.0706
 0.5063
 0.7313
 0.3003
 1.8423
 0.2580
-1.4946
[torch.FloatTensor of size 16]


 0.0506 -0.8122  0.1810 -0.5836 -0.4300 -0.9669  0.5346  0.7780
-0.9813  0.0706  0.5063  0.7313  0.3003  1.8423  0.2580 -1.4946
[torch.FloatTensor of size 2x8]



In [14]:
# Bridging numpy arrays and torch tensors
# Share memory: changing one will change the other

# torch to numpy: x.numpy()
# numpy to torch: torch.from_numpy(x)

a = torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [15]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [16]:
# Change a, observe that b changes too
a.add(1)
print(a)
print(b)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]

[1. 1. 1. 1. 1.]


In [18]:
# Convert numpy array to torch Tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



In [20]:
# Check if you have CUDA
torch.cuda.is_available()

False

In [19]:
## AUTOGRAD: automatic differentiation for all Tensor operations
# autograd.Variable: wraps a Tensor and records the history of operations applied to it
# autograd.Function: implements forward and backward definitions of an autograd operations

from torch.autograd import Variable

In [26]:
x = Variable(torch.ones(2,2), requires_grad=True)
print(x)

y = x + 2
print(y)

Variable containing:
 1  1
 1  1
[torch.FloatTensor of size 2x2]

Variable containing:
 3  3
 3  3
[torch.FloatTensor of size 2x2]



In [28]:
print('x grad_fn: ', x.grad_fn)
# y was result of tensor operation, so y has a gradient function
print('y grad_fn: ', y.grad_fn)

x grad_fn:  None
y grad_fn:  <AddBackward0 object at 0x7f5fbc164860>


In [30]:
z = y * y * 3
out = z.mean()
print(z, out)
print(z.grad_fn)
print(out.grad_fn)

Variable containing:
 27  27
 27  27
[torch.FloatTensor of size 2x2]
 Variable containing:
 27
[torch.FloatTensor of size 1]



In [37]:
print(x.grad)
# gradient of x = (1/4) * sum_i(z_i, z_i) = 3(x_i + 2)^2 = 4.5

Variable containing:
 4.5000  4.5000
 4.5000  4.5000
[torch.FloatTensor of size 2x2]



In [44]:
x = torch.randn(3)
x = Variable(x, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

Variable containing:
-1075.5979
  270.2129
 1648.1222
[torch.FloatTensor of size 3]



In [47]:
gradients = torch.FloatTensor([0.1, 1.0, 0.0001])
y.backward(gradients)

print(x.grad)

Variable containing:
  614.4000
 6144.0000
    0.6144
[torch.FloatTensor of size 3]



In [22]:
# Neural Networks
import torch.nn as nn
import torch.nn.functional as F

# Module is base class for all neural nets
class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels 5x5 square
        # convolution kernel
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        # y = w*x + b
        # Linear: (in_features, out_features, bias = True)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2,2) window
        # Requires: x is one input image channel (to pass into conv1 first)
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # Only need to specify one number if size if square
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x)) # flatten Tensor into 1d
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    # backward function is automatically defined using autograd

    def num_flat_features(self, x):
        size = x.size()[1:] # all dimensions except the batch dimension
                            # (meaning all except numer of channels?)
        num_features = 1
        for s in size:
            num_features *= s # multiply all dimensionalities (except batch)
        return num_features

net = Net()
print(net)

Net(
  (conv1): Conv2d (1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d (6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120)
  (fc2): Linear(in_features=120, out_features=84)
  (fc3): Linear(in_features=84, out_features=10)
)


In [11]:
x = torch.rand(5,3)
print(x)
print(x.size())
print(x.size()[1:])


 0.3926  0.6371  0.1068
 0.9931  0.7634  0.4116
 0.1922  0.9072  0.5184
 0.7649  0.2063  0.2753
 0.4100  0.4822  0.9047
[torch.FloatTensor of size 5x3]

torch.Size([5, 3])
torch.Size([3])


In [17]:
# learnable parameters of a net are net.parrameters()
params = list(net.parameters()) # just net.parameters is a generator object
print('Length of params: ', len(params))
print('conv1\'s .weight: ', params[0].size())

Length of params:  10
conv1's .weight:  torch.Size([6, 1, 5, 5])


In [23]:
# input and output of forward pass is an autograd.Variable
input = Variable(torch.randn(1, 1, 32, 32)) # 32 x 32 images
out = net(input)
print(out)

Variable containing:
1.00000e-02 *
  9.5090 -7.7049 -3.2734 -8.9001 -6.3531 -2.8671 -7.9464  4.8344  2.3587 -0.5596
[torch.FloatTensor of size 1x10]



In [26]:
# set gradients of all model parameters to zero, give backprops random gradients
# set gradients to zero before backprop because pytorch accumulates gradients
# on each subsequent backward pass
net.zero_grad()
out.backward(torch.randn(1, 10))

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

In [40]:
# LOSS FUNCTION
# takes the (output, target) pair of inputs, and computes a value
# that estimates how close they are

output = net(input)
target = Variable(torch.arange(1,11)) # dummy target, for example
criterion = nn.MSELoss() # mean-squared error

loss = criterion(output, target) # loss is a Variable (has gradient)
print('Loss: ', loss.data)

# follow computations backward
print('MSE Loss: ', loss.grad_fn)
print('Linear: ', loss.grad_fn.next_functions)
print('ReLU: ', loss.grad_fn.next_functions[0][0].next_functions[0][0])


Loss:  
 38.7070
[torch.FloatTensor of size 1]

MSE Loss:  <MseLossBackward object at 0x7f570a08b630>
Linear:  ((<AddmmBackward object at 0x7f573caebda0>, 0),)
ReLU:  <ExpandBackward object at 0x7f57386c1f28>


In [42]:
# BACKPROP
# all you need to do is call loss.backward() to backprop error

net.zero_grad() # zero the gradient buffers of all params

print('conv1.bias.grad before backward: ')
print(net.conv1.bias.grad)

loss.backward()

print('conv1.bias.grad after backward: ')
print(net.conv1.bias.grad)

conv1.bias.grad before backward: 
Variable containing:
 0
 0
 0
 0
 0
 0
[torch.FloatTensor of size 6]

conv1.bias.grad after backward: 
Variable containing:
-0.1310
-0.0553
 0.0154
 0.0677
-0.0999
-0.0942
[torch.FloatTensor of size 6]



In [43]:
# Update weights

# Can do weight = weight - learning_rate * gradient
learning_rate = 0.01
for f in net.parameters():
    f.data.sub_(f.grad.data * learning_rate)

# Better: use one of built in optimizers
import torch.optim as optim

optimizer = optim.SGD(net.parameters(), lr=0.01)

# in training loop:
optimizer.zero_grad() # zero the gradient buffers
output = net(input)
loss = criterion(output, target)
loss.backward()
optimizer.step() # Does the update

